### ISSUE TITLE
BUG: Crash due to referencing object map without join condition

### ISSUE THREAD

**Issue by nicolastoira** [oeg-upm/morph-kgc#110]
The execution of `python3 -m morph_kgc morph.ini`  is failing after writing to the output file. Trying to convert JSON to RDF.

Configuration file:

```
[DEFAULT]
main_dir: /lib

[CONFIGURATION]
output_file: knowledge-graph.nt

[DataSource1]
mappings: ml_generated_mapping.ttl
```

Error:

```
INFO | 2022-12-01 10:26:29,037 | 620 mapping rules retrieved.
INFO | 2022-12-01 10:26:29,414 | Mapping partition with 419 groups generated.
INFO | 2022-12-01 10:26:29,415 | Maximum number of rules within mapping group: 24.
INFO | 2022-12-01 10:26:29,434 | Mappings processed in 4.174 seconds.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 363, in _materialize_mapping_partition
    data = _materialize_mapping_rule(mapping_rule, mappings_df, config)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 332, in _materialize_mapping_rule
    merged_data = _merge_data(data, parent_data, mapping_rule, 'object_join_conditions')
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 258, in _merge_data
    return data.merge(parent_data, how='inner', left_on=child_join_references, right_on=parent_join_references)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 9351, in merge
    return merge(
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 122, in merge
    return op.get_result()
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 716, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 967, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 941, in _get_join_indexers
    return get_join_indexers(
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1489, in get_join_indexers
    llab, rlab, shape = (list(x) for x in zipped)
ValueError: not enough values to unpack (expected 3, got 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/__main__.py", line 21, in <module>
    process_materialization(mappings, config)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/engine.py", line 44, in process_materialization
    materializer.materialize_concurrently()
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 406, in materialize_concurrently
    num_triples = sum(pool.starmap(_materialize_mapping_partition,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: not enough values to unpack (expected 3, got 0)
```

Is it some known issue of the code, or it could be due to input data or used RML mapping? Thanks.

**Comment by ArenasGuerreroJulian** [comment]
Hi @nicolastoira ,

This looks like an error with the joins. Please revise your referencing object maps in the mappings, and if the error persists attach them to the issue so that I can have a look.

**Comment by nicolastoira** [comment]
The RML mapping file works fine with rmlmapper. It is a problem when a referenced child is not found in the data? We report in the RML mapping all the possible mappings and join conditions, but the properties could be missing in the JSON data. RmlMapper for example, only generates triples when it finds a match in the data, does morph-kgc work similarly? Thanks.

Example:
```
 rr:predicateObjectMap [ rr:objectMap [ rr:joinCondition [ rr:child "example.id" ;
                            rr:parent "id" ] ;
                    rr:parentTriplesMap :ExampleMapping ] ;
            rr:predicate prefix:example ]
```

**Comment by ArenasGuerreroJulian** [comment]
AFAIK Morph-KGC should be working in that case. Because of the line in which it is failing it looks like a referencing object map with multiple join conditions (not only one as the example you attach).

To go into this I would need to go see the detailed mapping (logical sources and parent triples map) and data.

**Comment by nicolastoira** [comment]
I cannot provide data at the moment due to sensitive data. I'll try to reproduce it with an example. Few things to consider about our mappings:
- We do have nested mappings. The JSON schema is nested and therefore we have mappings called into a join condition that in their definition calls one or more mappings with a join condition for the nested properties on the lower level.
- In order to access the data in a lower level, we use a join condition and call another mapping. The called mapping defines an iterator which finds multiple results and matches them, for example:
```
:hasBodySiteMapping a rr:TriplesMap ;
    rml:logicalSource [ rml:iterator "$..hasBodySite" ;
            rml:referenceFormulation ql:JSONPath ;
            rml:source "patient-1.json" ]
```
which is for example invoked by the predicateObjectMap:
```
[ rr:objectMap [ rr:joinCondition [ rr:child "hasBodySite.id" ;
                            rr:parent "id" ] ;
                    rr:parentTriplesMap :hasBodySiteMapping ]
```

JSON data could be:
```
{
"upperkey": {
  "hasBodySite": {
    "id": "id_value"
}
}
```
}

**Comment by ArenasGuerreroJulian** [comment]
I am still missing some informations about themappings such as the logical source of the child triples map. I assumed it is accessing the same `patient-1.json` file and completed the mapping:

```ttl
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .

<TM1>
    rml:logicalSource [
        rml:iterator "$..hasBodySite" ;
        rml:referenceFormulation ql:JSONPath ;
        rml:source "data.json"
    ];
    rr:subjectMap [
        rr:template "http://example.com/{id}"
    ];
    rr:predicateObjectMap [
        rr:predicate foaf:id ;
        rr:objectMap [
            rml:reference "id"
        ]
    ].

<TM2>
    rml:logicalSource [
        rml:iterator "$.upperkey" ;
        rml:referenceFormulation ql:JSONPath ;
        rml:source "data.json"
    ];
    rr:subjectMap [
        rr:template "http://example.com/{hasBodySite.id}"
    ];
    rr:predicateObjectMap [
        rr:predicate foaf:id_join ;
        rr:objectMap [
            rr:parentTriplesMap <TM1>;
            rr:joinCondition [
                rr:child "hasBodySite.id" ;
                rr:parent "id"
            ] ;
        ]
    ].
```

This is working. Are this similar to your mappings?

**Comment by nicolastoira** [comment]
Yes quite similar the nesting of mappings is missing. I tried to build a simple example but it's giving another error. Anyway I think I'll go for an alternative solution.

Command:
`python3 -m morph_kgc morph.ini`

Config file:
```
[DEFAULT]
main_dir: /lib

[CONFIGURATION]
output_file: knowledge-graph.nt

[DataSource1]
mappings: morph_mapping.ttl
```

Current error:
```
INFO | 2022-12-02 15:57:44,314 | 11 mapping rules retrieved.
INFO | 2022-12-02 15:57:44,350 | Mapping partition with 9 groups generated.
INFO | 2022-12-02 15:57:44,351 | Maximum number of rules within mapping group: 2.
INFO | 2022-12-02 15:57:44,353 | Mappings processed in 0.929 seconds.
INFO | 2022-12-02 15:57:44,561 | Number of triples generated in total: 9.
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/__main__.py", line 21, in <module>
    process_materialization(mappings, config)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/engine.py", line 44, in process_materialization
    triples = materializer.materialize_concurrently(to_file)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 434, in materialize_concurrently
    triples_to_file(triples, self.config, self.mapping_partitions.iloc[0]['mapping_partition'])
AttributeError: 'list' object has no attribute 'iloc'
```

Mapping file:
```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix : <https://example/example#> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix example: <https://example/example#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

:AllergyMapping a rr:TriplesMap ;
    rml:logicalSource [ rml:iterator "$.content.example:Allergy[*]" ;
            rml:referenceFormulation ql:JSONPath ;
            rml:source "morph_patient.json" ] ;
    rr:predicateObjectMap [ rr:objectMap [ rml:reference "example:hasLastReactionDateTime" ;
                    rr:datatype xsd:dateTime ] ;
            rr:predicate example:hasLastReactionDateTime ],
        [ rr:objectMap [ rr:joinCondition [ rr:child "example:hasSubstance.id" ;
                            rr:parent "id" ] ;
                    rr:parentTriplesMap :hasSubstanceMapping ] ;
            rr:predicate example:hasSubstance ],
        [ rr:objectMap [ rml:reference "example:hasFirstRecordDateTime" ;
                    rr:datatype xsd:dateTime ] ;
            rr:predicate example:hasFirstRecordDateTime ] ;
    rr:subjectMap [ rr:class example:Allergy ;
            rr:template "https://example/Allergy-{id}" ] .

:hasSubstanceMapping a rr:TriplesMap ;
    rml:logicalSource [ rml:iterator "$..example:hasSubstance" ;
            rml:referenceFormulation ql:JSONPath ;
            rml:source "morph_patient.json" ] ;
    rr:predicateObjectMap [ rr:objectMap [ rr:joinCondition [ rr:child "example:hasCode.termid" ;
                            rr:parent "termid" ] ;
                    rr:parentTriplesMap :hasCodeMappingTerminology ] ;
            rr:predicate example:hasCode ],
        [ rr:objectMap [ rml:reference "example:hasGenericName" ;
                    rr:datatype xsd:string ] ;
            rr:predicate example:hasGenericName ],
        [ rr:objectMap [ rr:joinCondition [ rr:child "example:hasCode.id" ;
                            rr:parent "id" ] ;
                    rr:parentTriplesMap :hasCodeMappingCode ] ;
            rr:predicate example:hasCode ] ;
    rr:subjectMap [ rr:class example:Substance ;
            rr:template "https://example/Substance-{id}" ] .


:hasCodeMappingCode a rr:TriplesMap ;
    rml:logicalSource [ rml:iterator "$..example:hasCode" ;
            rml:referenceFormulation ql:JSONPath ;
            rml:source "morph_patient.json" ] ;
    rr:predicateObjectMap [ rr:objectMap [ rml:reference "example:hasIdentifier" ;
                    rr:datatype xsd:string ] ;
            rr:predicate example:hasIdentifier ] ;
    rr:subjectMap [ rr:class example:Code ;
            rr:template "https://example/Code-{id}" ] .

:hasCodeMappingTerminology a rr:TriplesMap ;
    rml:logicalSource [ rml:iterator "$..example:hasCode" ;
            rml:referenceFormulation ql:JSONPath ;
            rml:source "morph_patient.json" ] ;
    rr:predicateObjectMap [ rr:objectMap [ rml:reference "iri" ;
                    rr:termType rr:IRI ] ;
            rr:predicate rdf:type ] ;
    rr:subjectMap [ rr:template "https://example/Code-{termid}" ] .
```

JSON file:
```
{
    "content": {
            "example:Allergy": [
                {
                "id" : "34634634",
                "example:hasFirstRecordDateTime": "2022-04-24T11:55:43.304Z",
                "example:hasLastReactionDateTime": "2022-03-31T11:55:43.304Z",
                "example:hasSubstance": {
                    "id": "48568568",
                    "example:hasGenericName": "jghjfghmjfhg",
                    "example:hasCode":{
                        "id": "fgjfgjfgkj5zue",
                        "example:hasIdentifier": "45zrtgf"
                    }
                }
            }
        ]
    }     
}
```

**Comment by ArenasGuerreroJulian** [comment]
This bug is related to `v2.3.0`. If you go back to `v2.2.0` this should be working:

```
pip install morph_kgc==2.2.0
```

I am preparing a bug-fix release for this new error.

**Comment by ArenasGuerreroJulian** [comment]
Hi @nicolastoira ,

I tried your latest mapping with the new version `2.3.1` and it is working. Could you confirm to close the issue?

**Comment by nicolastoira** [comment]
For the simple case I shared it's working as you said. If I try with a more complete example it still fails with the initial error it seems. RDF file is partially generated.
```
INFO | 2022-12-07 08:56:04,520 | 620 mapping rules retrieved.
INFO | 2022-12-07 08:56:04,878 | Mapping partition with 417 groups generated.
INFO | 2022-12-07 08:56:04,879 | Maximum number of rules within mapping group: 24.
INFO | 2022-12-07 08:56:04,898 | Mappings processed in 15.891 seconds.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 371, in _materialize_mapping_group_to_file
    data = _materialize_mapping_rule(mapping_rule, mappings_df, config)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 337, in _materialize_mapping_rule
    merged_data = _merge_data(data, parent_data, mapping_rule, 'object_join_conditions')
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/materializer.py", line 259, in _merge_data
    return data.merge(parent_data, how='inner', left_on=child_join_references, right_on=parent_join_references)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 9351, in merge
    return merge(
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 122, in merge
    return op.get_result()
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 716, in get_result
    join_index, left_indexer, right_indexer = self._get_join_info()
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 967, in _get_join_info
    (left_indexer, right_indexer) = self._get_join_indexers()
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 941, in _get_join_indexers
    return get_join_indexers(
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 1489, in get_join_indexers
    llab, rlab, shape = (list(x) for x in zipped)
ValueError: not enough values to unpack (expected 3, got 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nicola/workspace/venv/lib/python3.8/site-packages/morph_kgc/__main__.py", line 46, in <module>
    pool.starmap(_materialize_mapping_group_to_file, zip(mapping_groups, repeat(mappings_df), repeat(config))))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: not enough values to unpack (expected 3, got 0)
```

**Comment by ArenasGuerreroJulian** [comment]
Thanks @nicolastoira ,

If you provide more detail to reproduce the error I can  through to it like in the previous cases.

**Comment by ArenasGuerreroJulian** [comment]
The error is caused because a referencing object does not have a join condition:
```
rr:predicateObjectMap [ rr:objectMap [ rr:parentTriplesMap :DataProviderInstituteMapping ] ;
            rr:predicate example:hasDataProviderInstitute ],
```
